//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Carlos Rios on 7/21/16.
//  Copyright (c) 2016 Refundo Inc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CreateOrderRequest
{
}

struct CreateOrderResponse
{
}

struct CreateOrderViewModel
{
}
